// Generate a file that exports all the icons in the icons folder
import fs from 'fs-extra';
import path from 'path';

const iconsPath = path.join(
  __dirname,
  '..',
  '..',
  'src',
  'components',
  'icons'
);

const exportLineFormat = (
  acc: string,
  component: string,
  fileName: string
) => `${acc}
export { default as ${component} } from './${fileName}';
`;

// get all ".tsx" files, extract the function name and add it to the list
const iconFiles = fs
  .readdirSync(iconsPath)
  .filter((file) => file.endsWith('.tsx') && !file.endsWith('.stories.tsx'));

const exportFile = iconFiles.reduce((acc, file) => {
  const content = fs.readFileSync(path.join(iconsPath, file), 'utf-8');
  const matches = content.match(/export default function (\w+)/);
  if (matches) {
    return exportLineFormat(acc, matches[1], file.replace('.tsx', ''));
  }
  return acc;
}, '');

// save file, replacing the old one
fs.writeFileSync(
  path.join(iconsPath, 'index.ts'),
  `// This file is auto-generated by tools/scripts/generate-icons.ts
${exportFile}`
);

console.log(`Icons generated at ${iconsPath}`);
