query activity($id: String!) {
  activity(id: $id) {
    id
    action
    read
    source {
      ... on User {
        did
        username
      }
      ... on Organization {
        did
        orgname
        name
        image
      }
    }
    target {
      ... on User {
        did
        username
      }
      ... on Organization {
        did
        orgname
        name
        image
      }
    }
    createdAt
    metadata {
      ... on PDAMetadata {
        issuer
        pda
        status
        signedBy
        expirationDate
        dataModel
      }
      ... on RequestMetadata {
        verifier
        owner
        request
        dataRequestStatus: status
      }
      ... on ProofMetadata {
        verifier
        owner
        proof
        proofRequest: request
        proofStatus: status
      }

      ... on DataModelMetadata {
        creator
        dataModelId: dataModel
        signedBy
      }

      ... on UserMetadata {
        user
      }

      ... on OrganizationMetadata {
        organization
        users
        usersAdmin
        verified
      }
    }
  }
}

query explorer_transactions($skip: Int, $take: Int) {
  activities(filter: { skip: $skip, take: $take }) {
    id
    action
    createdAt
  }
}

query last_transactions {
  activities(filter: { skip: 0, take: 10 }) {
    id
    action
    createdAt
  }
}
