query me {
  me {
    id
    did
    username
    totalFileSize
    accesses {
      role
      organization {
        image
        name
        did
        usernameUpdatedAt
        verified
      }
    }
  }
  myPDACount
}
