import { ThemeProvider, theme } from '@/theme'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  if (typeof window !== 'undefined' && process.env.NODE_ENV === 'development') {
    (window as any).theme = theme;
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <p>Root</p>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
