fragment pda on PrivateDataAsset {
  id
  status
  status

  dataAsset {
    title
    description
    expirationDate
    image
    issuanceDate

    organization {
      id
      image
      name
      gatewayId
    }
    issuer {
      ...user
    }
    owner {
      ...user
    }
    dataModel {
      id
      createdAt
      tags
    }
    claim
    claimArray {
      label
      metadata
      property
      description
      type
      value
    }
  }
}
