fragment user on User {
  id
  gatewayId
  profilePicture
  email
  primaryWallet {
    address
  }
  wallets {
    address
  }
  createdAt
  updatedAt
}

fragment min_user on User {
  id
  gatewayId
  profilePicture
  createdAt
}
