query dataModels($creatorUserId: String!, $skip: Int, $take: Int) {
  dataModels(
    filter: { user: { type: USER_ID, value: $creatorUserId } }
    skip: $skip
    take: $take
  ) {
    id
    title
    createdAt
  }
}

query dataModelById($id: String!) {
  dataModel(id: $id) {
    title
    description
    tags
    createdBy {
      ...min_user
    }
    organization {
      ...org
    }
    schema
    consumptionPrice
  }
}

query dataModelsByOrg($organizationId: String!, $skip: Int, $take: Int) {
  dataModels(
    filter: { organization: { type: ORG_ID, value: $organizationId } }
    skip: $skip
    take: $take
  ) {
    id
    title
    createdAt
  }
}

query myDataModelsCount {
  myDataModelsCount
}

query myDataModelsCountOrg($orgGatewayId: String!) {
  myDataModelsCount(
    filter: { organization: { type: GATEWAY_ID, value: $orgGatewayId } }
  )
}
