query dataModelById($id: String!) {
  dataModel(id: $id) {
    title
    description
    tags
    createdBy {
      ...min_user
    }
    organization {
      ...org
    }
    schema
    consumptionPrice
  }
}

query dataModels($skip: Int, $take: Int) {
  dataModels(skip: $skip, take: $take) {
    id
    title
    consumptionPrice
    pdasIssuedCount
    createdAt
  }
}

query dataModelsByUser($user: UserIdentificationInput, $skip: Int, $take: Int) {
  dataModels(filter: { user: $user }, skip: $skip, take: $take) {
    id
    title
    consumptionPrice
    pdasIssuedCount
    createdAt
  }
}

query dataModelsByOrg(
  $organization: OrganizationIdentificationInput
  $skip: Int
  $take: Int
) {
  dataModels(
    filter: { organization: $organization }
    skip: $skip
    take: $take
  ) {
    id
    title
    consumptionPrice
    pdasIssuedCount
    createdAt
  }
}

query dataModelsCount {
  dataModelsCount
}

query dataModelsByUserCount($user: UserIdentificationInput) {
  dataModelsCount(filter: { user: $user })
}

query dataModelsByOrgCount($organization: OrganizationIdentificationInput) {
  dataModelsCount(filter: { organization: $organization })
}
