query explorer_request_templates_featured {
  dataRequestTemplates(take: 4) {
    id
    name
    dataRequestsCount
    createdAt
  }
}

query explorer_request_template_detail_overview($id: String!) {
  dataRequestTemplate(id: $id) {
    id
    name
    description
    tags
    uniqueVerifiersCount
    dataRequestsCount
    dataModels {
      id
      title
      arweaveUrl
      schema
      pdasIssuedCount
    }
    dataRequests {
      id
      status
    }
    schema
    user {
      id
      gatewayId
      displayName
    }
    organization {
      id
      gatewayId
      name
    }
    createdAt
  }
}

query explorer_request_template_detail_verifiers($id: String!) {
  dataRequestTemplate(id: $id) {
    id
    name
    tags
    dataRequestsCount
    user {
      id
      gatewayId
      displayName
      profilePicture
    }
  }
}
