query explorer_data_models_featured {
  dataModels(take: 4) {
    id
    title
    description
    createdBy {
      ...min_user
    }
    organization {
      ...org
    }
    consumptionPrice
    pdasIssuedCount
  }
}

query explorer_data_models_list(
  $filter: FilterDataModelInput
  $skip: Int = 0
  $order: JSON
) {
  dataModels(filter: $filter, skip: $skip, take: 12, order: $order) {
    id
    title
    description
    createdBy {
      ...min_user
    }
    organization {
      ...org
    }
    consumptionPrice
    pdasIssuedCount
  }
}

query explorer_data_models_metadata {
  dataModelsMetadata {
    tags
    consumptionPrice
    issuedCount
  }
}

query explorer_data_model_detail_overview($id: String!) {
  dataModel(id: $id) {
    id
    title
    description
    arweaveUrl
    createdBy {
      ...min_user
    }
    organization {
      ...org
    }
    tags
    consumptionPrice
    pdasIssuedCount
    uniqueIssuersCount
    revenueGenerated
    schema
    createdAt
    permissioning
    allowedUsers {
      ...min_user
    }
    allowedOrganizations {
      ...org
    }
  }
}

query explorer_data_model_detail_issuers($id: String!) {
  dataModel(id: $id) {
    id
    title
    tags
  }
}

query explorer_data_model_detail_request_templates($id: String!) {
  dataModel(id: $id) {
    id
    title
    tags
  }
}

query explorer_issuers_by_data_model($id: String!) {
  issuersByDataModel(id: $id) {
    issuer {
      ... on User {
        id
        displayName
        gatewayId
        profilePicture
      }
      ... on Organization {
        id
        name
        gatewayId
        image
      }
    }
    count
  }
}

query explorer_issuers_by_data_model_count($id: String!) {
  issuersByDataModelCount(id: $id)
}
