query me {
  me {
    id
    displayName
    profilePicture
    gatewayId
    accesses {
      role
      organization {
        id
        image
        name
        gatewayId
      }
    }
    authentications {
      id
      type
      data {
        address
        chain
      }
    }
  }
}
