query pdas {
  credentials {
    id
    title
    image
    status
  }
}

query pda($id: String!) {
  PDA(id: $id) {
    ...pda
  }
}

query received_pdas($take: Float!, $skip: Float!) {
  myPDAs(skip: $skip, take: $take) {
    id
    status
    dataAsset {
      title
      image
      organization {
        id
        image
        name
        gatewayId
      }
      owner {
        ...min_user
      }
      issuer {
        ...min_user
      }
    }
  }
}

query issued_pdas($take: Float!, $skip: Float!) {
  issuedPDAs(skip: $skip, take: $take) {
    id
    status
    dataAsset {
      title
      image
      organization {
        id
        image
        name
        gatewayId
      }
      issuer {
        ...min_user
      }
      owner {
        ...min_user
      }
    }
  }
}

query issued_pdas_by_org(
  $take: Float!
  $skip: Float!
  $organization: OrganizationIdentificationInput!
) {
  issuedPDAs(
    skip: $skip
    take: $take
    filter: { organization: $organization }
  ) {
    id
    status
    issuanceDate
    status

    dataAsset {
      title
      organization {
        gatewayId
      }
      owner {
        ...min_user
      }
      dataModel {
        id
      }
    }
  }
}

query countIssuedPdasByOrg($organization: OrganizationIdentificationInput!) {
  issuedPDAsCount(filter: { organization: $organization })
}
