query pdas {
  credentials {
    id
    title
    image
    status
  }
}

query pda($id: String!) {
  PDAbyId(id: $id) {
    id
    issuanceDate
    dataAsset {
      title
      description
      expirationDate
      image
      organization {
        name
        image
        gatewayId
      }
      issuer {
        id
        userId
        data
        user {
          gatewayId
          createdAt
        }
      }
      owner {
        id
        data
        user {
          gatewayId
          createdAt
        }
      }
      dataModel {
        id
        createdAt
        tags
      }
      claim
      claimArray {
        label
        metadata
        property
        description
        type
        value
      }
      status
    }
  }
}

query received_pdas($take: Float!, $skip: Float!) {
  myPDAs(skip: $skip, take: $take) {
    id
    dataAsset {
      title
      organization {
        image
        name
        gatewayId
      }
      issuer {
        data
        user {
          gatewayId
        }
      }
      status
    }
  }
}

query issued_pdas($take: Float!, $skip: Float!) {
  myPDAs(skip: $skip, take: $take) {
    id
    dataAsset {
      title
      image
      status
    }
  }
}
