query pdas {
  credentials {
    id
    title
    image
    status
  }
}

query pda($id: String!) {
  PDAbyId(id: $id) {
    id
    dataAsset {
      title
      description
      expirationDate
      issuerOrganization {
        image
        gatewayId
      }
      issuerUser {
        gatewayId
      }
      recipientUser {
        gatewayId
      }
      issuerAuth {
        data
      }
      recipientAuth {
        data
      }
      dataModel {
        id
        createdAt
      }
      claim
      status
      issuerUser {
        id
      }
    }
  }
}

query received_pdas($take: Float!, $skip: Float!) {
  myPDAs(skip: $skip, take: $take) {
    id
    dataAsset {
      title
      issuerOrganization {
        image
        name
        gatewayId
      }
      issuerUser {
        gatewayId
      }
      status
    }
  }
}

query sent_pdas($take: Float!, $skip: Float!) {
  myPDAs(skip: $skip, take: $take) {
    id
    dataAsset {
      title
      image
      status
    }
  }
}
