query received_proofs($take: Float!, $skip: Float!) {
  receivedProofs(skip: $skip, take: $take) {
    id
    totalCost
    facilitationFee
    createdAt
    arweaveUrl

    owner {
      id
      user {
        gatewayId
        profilePicture
      }
      data
    }

    data {
      dataModels {
        id
      }
      PDAs {
        id
        claim
        dataModel {
          id
        }
        issuer {
          id
        }
        organization {
          id
          gatewayId
        }
        owner {
          id
        }
      }
    }

    verifier {
      user {
        gatewayId
        profilePicture
      }
    }

    organization {
      gatewayId
      image
    }

    dataRequest {
      id
      dataRequestTemplate {
        id
      }
    }
  }
}
query countReceivedProofs {
  receivedProofsCount
}

query sent_proofs($take: Float!, $skip: Float!) {
  sentProofs(skip: $skip, take: $take) {
    id

    data {
      PDAs {
        id
      }
    }

    verifier {
      user {
        gatewayId
        profilePicture
      }
    }

    dataRequest {
      id
      dataRequestTemplate {
        id
      }
    }
  }
}

query proof($id: String!) {
  proof(id: $id) {
    id
    totalCost
    facilitationFee
    createdAt
    arweaveUrl

    data {
      dataModels {
        id
        title
        consumptionPrice
      }
      PDAs {
        id
        title
        claim
        dataModel {
          id
        }
        issuer {
          id
          user {
            gatewayId
            profilePicture
          }
        }
        organization {
          id
          name
          gatewayId
          image
        }
        owner {
          id
        }
      }
    }

    verifier {
      user {
        gatewayId
        profilePicture
      }
    }

    dataRequest {
      id
      status
      dataRequestTemplate {
        id
      }
    }
  }
}

query proofsByPDAIds($pdaIds: [String!]!) {
  proofsByPDAIds(pdaIds: $pdaIds) {
    id
    totalCost
    facilitationFee
    createdAt
    active
    data {
      dataModels {
        id
        title
        consumptionPrice
      }
      PDAs {
        id
        claim
        title
        dataModel {
          id
        }
        issuer {
          id
          user {
            gatewayId
            profilePicture
          }
        }
        organization {
          id
          name
          gatewayId
          image
        }
        owner {
          id
        }
      }
    }
    arweaveUrl
    organization {
      gatewayId
    }
    verifier {
      user {
        gatewayId
        profilePicture
      }
      data
    }
    dataRequest {
      id
      arweaveUrl
      status
      dataRequestTemplate {
        id
      }
    }
  }
}
