query requests {
  dataRequests {
    id
    status
    userVerifier {
      id
      gatewayId
    }
    createdAt
    dataRequestTemplate {
      id
    }
  }
}

query myRequestsReceived($take: Float!, $skip: Float!) {
  requestsReceived(skip: $skip, take: $take) {
    id
    status
    userVerifier {
      gatewayId
    }
    createdAt
    dataRequestTemplate {
      id
    }
  }
}

query requestsCount {
  requestsReceivedCount
}
