query requests {
  dataRequests {
    id
    status
    userVerifier {
      id
      gatewayId
    }
    createdAt
    dataRequestTemplate {
      id
    }
  }
}

query myRequestsReceived($take: Float!, $skip: Float!) {
  requestsReceived(skip: $skip, take: $take) {
    id
    status
    userVerifier {
      ...min_user
    }
    createdAt
    dataRequestTemplate {
      id
    }
  }
}

query requestsCount {
  requestsReceivedCount
}

query dataRequest($id: String!) {
  dataRequest(requestId: $id) {
    id
    dataUse
    status
    createdAt

    proofs {
      id
    }
    userVerifier {
      id
      gatewayId
      profilePicture
      displayName
    }
    dataRequestTemplate {
      id
      dataModels
    }
  }
}

query dataRequestValidData($requestId: String!) {
  findValidPDAsForRequest(requestId: $requestId) {
    required
    validData {
      provided
    }
  }
}
