query dataRequestTemplates(
  $user: UserIdentificationInput
  $skip: Float
  $take: Float
) {
  dataRequestTemplates(filter: { user: $user }, skip: $skip, take: $take) {
    id
    name
    createdAt
  }
}

query dataRequestTemplatesByOrg(
  $organization: OrganizationIdentificationInput
  $skip: Float
  $take: Float
) {
  dataRequestTemplates(
    filter: { organization: $organization }
    skip: $skip
    take: $take
  ) {
    id
    name
    createdAt
  }
}

query dataRequestTemplateById($id: String!) {
  dataRequestTemplate(id: $id) {
    id
    name
    description
    tags
    organization {
      ...org
    }
    createdAt
    schema
  }
}

query dataRequestTemplatesCount($user: UserIdentificationInput) {
  myDataRequestTemplatesCount(filter: { user: $user })
}

query dataRequestTemplatesCountOrg(
  $organization: OrganizationIdentificationInput
) {
  myDataRequestTemplatesCount(filter: { organization: $organization })
}
