query my_transactions($skip: Int, $take: Int, $organizationId: String) {
  myFinancialTransactions(
    skip: $skip
    take: $take
    organizationId: $organizationId
  ) {
    id
    value
    type
    transactionId
    createdAt
    action
  }
}

query my_transactions_count($organizationId: String) {
  myFinancialTransactionsCount(organizationId: $organizationId)
}
