query my_transactions($skip: Int, $take: Int) {
  myFinancialTransactions(skip: $skip, take: $take) {
    id
    value
    type
    transactionId
    createdAt
    action
  }
}

query my_transactions_count {
  myFinancialTransactionsCount
}
