query check_username_avaibility($username: String!) {
  checkUsernameAvailability(username: $username)
}

query get_user_info($identification: UserIdentificationInput!) {
  user(input: $identification) {
    id
    displayName
    gatewayId
    profilePicture
    createdAt
  }
}
